/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: arrow_w11_h11_n                                       *
* Dimensions:  11 * 11                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned long acarrow_w11_h11_n[] = {
  0x00000000, 0x00000000, 0x00000000, 0x00000000, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0x00000000, 0x0000FFFF, 0x0000F3F8, 0x000099C2, 0x00002325, 0x00000000, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0x00003C47, 0x0000FFFF, 0x0000F8F5, 0x0000FFF9, 0x0000FFFF, 0x000093A7, 0x00002325, 0x00000000, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0x00004E34, 0x0000CDF5, 0x0000FCF6, 0x0000E4F9, 0x0000CBFF, 0x0000D8FF, 0x0000E8FF, 0x000093A7, 0x00002325, 0x00000000, 0xFFFF00FF,
  0xFFFF00FF, 0x00004E34, 0x0000FBFF, 0x0000CBFF, 0x0000D0FF, 0x0000CFFF, 0x0000C4FF, 0x0000C5FF, 0x0000C6FF, 0x00002325, 0xFF000000,
  0xFFFF00FF, 0xFF000000, 0x0000ADCD, 0x0000D6FF, 0x0000CEFF, 0x0000C4FF, 0x0000BCFF, 0x0000B2FF, 0x0000B9FF, 0x00007DBB, 0xFF000000,
  0xFFFF00FF, 0xFFFF00FF, 0x0000604E, 0x0000E3FF, 0x0000C4FF, 0x0000BCFF, 0x0000B3FF, 0x0000B9FF, 0x00006A9F, 0xFF000000, 0xFF000000,
  0xFFFF00FF, 0xFFFF00FF, 0xFF000000, 0x000095AE, 0x0000C2FF, 0x0000B3FF, 0x0000BAFF, 0x00006496, 0xFF000000, 0xFF000000, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00006B66, 0x0000C3FF, 0x0000BAFF, 0x00006393, 0xFF000000, 0xFF000000, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFF000000, 0x000084AC, 0x00006BA2, 0xFF000000, 0xFF000000, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFF000000, 0xFF000000, 0xFF000000, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF
};

GUI_CONST_STORAGE GUI_BITMAP bmarrow_w11_h11_n = {
  11, /* XSize */
  11, /* YSize */
  44, /* BytesPerLine */
  32, /* BitsPerPixel */
  (unsigned char *)acarrow_w11_h11_n,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_BMP8888
};

/* *** End of file *** */
