/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mark_left_8_16                                        *
* Dimensions:  8 * 16                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned long acmark_left_8_16[] = {
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00808080
};

GUI_CONST_STORAGE GUI_BITMAP bmmark_left_8_16 = {
  8, /* XSize */
  16, /* YSize */
  32, /* BytesPerLine */
  32, /* BitsPerPixel */
  (unsigned char *)acmark_left_8_16,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_BMP8888
};

/* *** End of file *** */
