/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mark_arrow_key_w_l                                    *
* Dimensions:  6 * 14                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned long acmark_arrow_key_w_l[] = {
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00E0E0E0,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF
};

GUI_CONST_STORAGE GUI_BITMAP bmmark_arrow_key_w_l = {
  6, /* XSize */
  14, /* YSize */
  24, /* BytesPerLine */
  32, /* BitsPerPixel */
  (unsigned char *)acmark_arrow_key_w_l,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_BMP8888
};

/* *** End of file *** */
