/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.12.                           *
*        Compiled Jun 29 2011, 15:28:21                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mark_arrow_yellow_d                                   *
* Dimensions:  20 * 10                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned long acmark_arrow_yellow_d[] = {
  0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080, 0x00105080,
  0xFFFF00FF, 0x00105080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00105080, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x0000C0FF, 0x0000C0FF, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF,
  0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0x00005080, 0x00005080, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF, 0xFFFF00FF
};

GUI_CONST_STORAGE GUI_BITMAP bmmark_arrow_yellow_d = {
  20, /* XSize */
  10, /* YSize */
  80, /* BytesPerLine */
  32, /* BitsPerPixel */
  (unsigned char *)acmark_arrow_yellow_d,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_BMP8888
};

/* *** End of file *** */
